### ISSUE TITLE
Apple Pay button doesn't visible on real ios device

### ISSUE THREAD

**Issue by v-pavlovskyi** [google-pay/flutter-plugin#173]
I don't know why, but on my iphone 11 pro doesn't show apple pay button, but on ios emulator there is a button.
For example, on Android device and on android emulator there is a google pay button. So, this means that the problems may not be with the library? 
Has anyone experienced this and how can this be resolved?

**Comment by JlUgia** [comment]
Hi @v-pavlovskyi, the issue is not specific to this library. I recommend you take a look at Apple Pay specific resources. Here are some users reporting similar issues ([1](https://stackoverflow.com/questions/49445470/applepay-is-not-working-in-real-device), [2](https://developer.apple.com/forums/thread/682392)).
