### ISSUE TITLE
Is UPI payment method supported?

### ISSUE THREAD

**Issue by nipun0212** [google-pay/flutter-plugin#33]
Hi,

Instead of card payment i want to enable in app gpay for UPI payments(in India). Is it possible?

**Comment by JlUgia** [comment]
Hi nipun0212!
The payment flow in India and rest-of-world have their differences. Since the UPI flow relies on the Google Pay app, requesting a payment in this context is as simple as issuing and intent with the required information (see https://developers.google.com/pay/india/api/android/in-app-payments). You can use the [`android_intent`](https://pub.dev/packages/android_intent) package to issue intents from Flutter.

We may consider adding this to the plugin too if the community thinks it's valuable. For now, we feel it's easier to simply issue the intent separately. Said so, you can still use the `pay_android` package in pub.dev to import the button widget, use it in your layout, and start the intent in response to the `onPressed` event.
Let me know if this helps.

**Comment by nipun0212** [comment]
Thanks @JlUgia . But how to make it work on ios and web?

**Comment by JlUgia** [comment]
UPI can be used on the Web with the [W3C payment standard](https://developers.google.com/pay/india/api/web/create-payment-method). To request payments on iOS, you can use an alternative path triggered from your servers with the [omnichannel API](https://developers.google.com/pay/india/api/otherapis/omnichannel/overview).

Note that none of these paths are included in this plugin yet.

**Comment by nipun0212** [comment]
Hi @JlUgia ,
Is adding UPI to GPay in the pipeline? This will help developers in India. UPI has already overtaken any other payment method in India. 
https://inc42.com/features/big-techs-upi-play-to-bite-credit-card-giants-visa-mastercard/

**Comment by JlUgia** [comment]
It ultimately comes down to you, other users of the plugin and the community overall.
There are a few questions to address, like determining whether it's useful to include UPI as part of this plugin or create a separate one; or if it's even necessary to add another plugin for this purpose altogether. 

Creating an UPI request on Android and Web is a rather lightweight task. For iOS, I'm seeing that different payment gateways have various SDKs to do so (eg.: [RazorPay](https://razorpay.com/docs/payment-gateway/payment-methods/upi-intent/ios/), [PayU](https://payumobile.gitbook.io/sdk-integration/ios/upi-standalone-ios/integration-steps)).  Is there a common and vendor-agnostic way to issue UPI payment requests on iOS?

As I think about it, a separate UPI plugin path becomes more apparent. It's probably worthwhile starting a discussion around the topic before we take next steps.

In the meantime, I'm seeing that [UPI plugins already exist in pub.dev](https://pub.dev/packages?q=upi). Do you have thoughts on them?
