### ISSUE TITLE
Google pay config for production

### ISSUE THREAD

**Issue by vanfresh** [google-pay/flutter-plugin#86]
This might be a silly question, but I notice the config for testing is: 

```
{
  "provider": "google_pay",
  "data": {
    "environment": "TEST",
```

However, I can't find the config for production.  Is it:

```
{
  "provider": "google_pay",
  "data": {
    "environment": "PRODUCTION",
```

or is the default production and I can just delete it?

**Comment by mkucharski17** [comment]
For me, changing the environment to PRODUCTION and updating merchantID to the production one was enough to make it work.

**Comment by JlUgia** [comment]
The bare minimum is to include the API versions to use and the list of allowed payment methods. For example:
```
{
  "provider": "google_pay",
  "data": {
    "environment": "TEST",
    "apiVersion": 2,
    "apiVersionMinor": 0,
    "allowedPaymentMethods": [ ... ]
  }
}
```
You can learn more about the fields available and whether they are required in [the API reference docs](https://developers.google.com/pay/api/android/reference/request-objects#IsReadyToPayRequest).

Said so, we recommend using a complete configuration so that your users get an informative and fulfilling payment experience. Take a look at the [example configuration files in the repo](https://github.com/google-pay/flutter-plugin/tree/main/pay/example/assets) for reference.
